# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.0.11
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: hongthaipro@gmail.com
author_name: leopham
contract_name: moting_app
deployment_language: python
preset_name: starter
project_name: voting

